  name: Generate Emojis JSON and Create Release

  on:
    workflow_dispatch:

  jobs:
    build-and-release:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Update packages
        run: npm update emojilib

      - name: npm install
        run: npm install

      - name: Get emojilib version
        id: get_version
        run: echo "::set-output name=version::$(npm show emojilib version)"

      - name: Create a release
        run: gh release create v${{ steps.get_version.outputs.version }} -t v${{ steps.get_version.outputs.version }} -n "Automated release of updated emojis.json for emojilib v${{ steps.get_version.outputs.version }}" ./emojis.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}